name: ltask Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["5.4"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Set module directory
        id: module
        shell: bash
        run: |
          VERSION="${{ matrix.version }}"
          VER="${VERSION//./}"
          echo "version=${VER}" >> $GITHUB_OUTPUT
      - name: Cache Lua dynamic library
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            lua/lua${{ steps.module.outputs.version }}/.lua
          key: lua-${{ matrix.os }}-${{ matrix.version }}-${{ hashFiles('Makefile') }}
          restore-keys: |
            lua-${{ matrix.os }}-${{ matrix.version }}-
      - name: Build Lua dynamic library
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: lua
        run: make lua${{ steps.module.outputs.version }}
        shell: bash
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run tests
        run: |
          go test -gcflags=all=-d=checkptr -v -race
        working-directory: ltask
        env:
          CGO_ENABLE: 0 # Disable CGO to ensure pure Go tests
