name: ltask Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        example: [webserver]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: yuchanns/actions-luamake@v1.0.0
        with:
          luamake-version: 'master'
      - name: Setup
        shell: bash
        run: |
          mkdir -p ./dynamic_test_example &&
          cat << 'EOF' > ./dynamic_test_example/action.yml
          runs:
            using: "composite"
            steps:
              - name: Setup example
                uses: ./.github/examples/${{ matrix.example }}
              - name: Lint (Linux)
                uses: golangci/golangci-lint-action@v8
                if: runner.os == 'ubuntu-latest'
                with:
                  version: "v2.1"
                  working-directory: examples/${{ matrix.example }}
              - name: Run example
                shell: bash
                run: |
                  go run .
                working-directory: examples/${{ matrix.example }}
                env:
                  CGO_ENABLED: 0
          EOF
      - name: Run
        uses: ./dynamic_test_example

